# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a99b03fbfd5893030a19b8a32934bfc12f081c0a7f820f4ab75f98c52f1fd1482c4305f27c6038442e94b9d0cb705c18347733754e129df0dd4ac210949c9ebd

test:
  secret_key_base: 0756259c23ce52953aaf9f14e464d7012c4a20a8b64ec36b1ff7265677c6adfb18a03fa0745dc1e31156692f65b3e5e92cd78a9d4ab28346bc24d724bd7a92dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
